export const documentation = [
  {
    id: 1,
    title: "Geração de pessoas",
    description:
      "O Usuário deve receber os dados completos da pessoa, podendo utilizar como parâmetros opcionais. sexo, idade, estado, cidade, quantidade de respostas e o formato.O formato da resposta deve mudar de acordo com a vontade do usuário, assim. Caso não seja informado a quantidade, deverá retornar apenas um.",
    route: "/person/:locale*/:gender/:quantity/",
    example: {
      nome: "Benjamin Roberto Theo Almeida",
      idade: 45,
      cpf: "665.010.127-32",
      rg: "38.825.667-9",
      data_nasc: "09/03/1977",
      mae: "Tatiane Sarah",
      pai: "Renan Raimundo Almeida",
      email: "benjamin-almeida77@igoralcantara.com.br",
      senha: "cQLQ634jd7",
      cep: "79620-386",
      endereco: "Rua F",
      numero: 661,
      bairro: "Nova Três Lagoas",
      cidade: "Três Lagoas",
      estado: "MS",
      telefone_fixo: "(67) 2874-8607",
      celular: "(67) 99759-7285",
      altura: "1.96",
      peso: 89,
    },

    params: [
      {
        name: "Formato de Dado",
        param: ":locale",
        route: "/person/BR",
        description: "Qual o tipo de dado deve retornar",
        options: [
          {
            name: "BR",
            description: "Retorna os dados em formato brasileiro",
          },
          {
            name: "US",
            description: "Retorna os dadoos em formato americano",
          },
        ],
        response: {
          code: 200,
          data: [
            {
              nome: "Benjamin Roberto Theo Almeida",
              idade: 45,
              cpf: "665.010.127-32",
              rg: "38.825.667-9",
              data_nasc: "09/03/1977",
              mae: "Tatiane Sarah",
              pai: "Renan Raimundo Almeida",
              email: "benjamin-almeida77@igoralcantara.com.br",
              senha: "cQLQ634jd7",
              cep: "79620-386",
              endereco: "Rua F",
              numero: 661,
              bairro: "Nova Três Lagoas",
              cidade: "Três Lagoas",
              estado: "MS",
              telefone_fixo: "(67) 2874-8607",
              celular: "(67) 99759-7285",
              altura: "1,96",
              peso: 89,
            },
          ],
        },
      },
      {
        name: "Quantidade",
        param: ":quantity",
        route: "/person/3",
        description: "Quantidade de pessoas que devem ser geradas",
        options: [
          {
            name: "Números Inteiros",
            description: "Diz quantas respostas deseja",
          },
        ],
        response: {
          code: 200,
          data: [
            {
              nome: "Benjamin Roberto Theo Almeida",
              idade: 45,
              cpf: "665.010.127-32",
              rg: "38.825.667-9",
              data_nasc: "09/03/1977",
              mae: "Tatiane Sarah",
              pai: "Renan Raimundo Almeida",
              email: "benjamin-almeida77@igoralcantara.com.br",
              senha: "cQLQ634jd7",
              cep: "79620-386",
              endereco: "Rua F",
              numero: 661,
              bairro: "Nova Três Lagoas",
              cidade: "Três Lagoas",
              estado: "MS",
              telefone_fixo: "(67) 2874-8607",
              celular: "(67) 99759-7285",
              altura: "1,96",
              peso: 89,
            },
            {
              nome: "Benjamin Roberto Theo Almeida",
              idade: 45,
              cpf: "665.010.127-32",
              rg: "38.825.667-9",
              data_nasc: "09/03/1977",
              mae: "Tatiane Sarah",
              pai: "Renan Raimundo Almeida",
              email: "benjamin-almeida77@igoralcantara.com.br",
              senha: "cQLQ634jd7",
              cep: "79620-386",
              endereco: "Rua F",
              numero: 661,
              bairro: "Nova Três Lagoas",
              cidade: "Três Lagoas",
              estado: "MS",
              telefone_fixo: "(67) 2874-8607",
              celular: "(67) 99759-7285",
              altura: "1,96",
              peso: 89,
            },
            {
              nome: "Benjamin Roberto Theo Almeida",
              idade: 45,
              cpf: "665.010.127-32",
              rg: "38.825.667-9",
              data_nasc: "09/03/1977",
              mae: "Tatiane Sarah",
              pai: "Renan Raimundo Almeida",
              email: "benjamin-almeida77@igoralcantara.com.br",
              senha: "cQLQ634jd7",
              cep: "79620-386",
              endereco: "Rua F",
              numero: 661,
              bairro: "Nova Três Lagoas",
              cidade: "Três Lagoas",
              estado: "MS",
              telefone_fixo: "(67) 2874-8607",
              celular: "(67) 99759-7285",
              altura: "1,96",
              peso: 89,
            },
          ],
        },
      },
      {
        name: "Sexo",
        param: ":gender",
        route: "/person/M",
        description: "Sexo da pessoa a ser gerada",
        options: [
          {
            name: "F",
            description: "Retorna apenas pessoas do sexo feminino",
          },
          {
            name: "M",
            description: "Retorna apenas pessoas do sexo masculino",
          },
        ],
        response: {
          code: 200,
          data: [
            {
              nome: "Benjamin Roberto Theo Almeida",
              idade: 45,
              cpf: "665.010.127-32",
              rg: "38.825.667-9",
              data_nasc: "09/03/1977",
              mae: "Tatiane Sarah",
              pai: "Renan Raimundo Almeida",
              email: "benjamin-almeida77@igoralcantara.com.br",
              senha: "cQLQ634jd7",
              cep: "79620-386",
              endereco: "Rua F",
              numero: 661,
              bairro: "Nova Três Lagoas",
              cidade: "Três Lagoas",
              estado: "MS",
              telefone_fixo: "(67) 2874-8607",
              celular: "(67) 99759-7285",
              altura: "1,96",
              peso: 89,
            },
          ],
        },
      },
    ],
  },
  {
    id: 2,
    title: "Gerador de Cartão",
    description: "O usuário deve receber dados válidos de cartão de crédito",
    route: "/creditcard/:quantity",
    example: {
      number: 3593347474642966,
      expiration: "18/12/2022",
      cvv: 559,
    },
    params: [
      {
        name: "Quantidade 2",
        param: ":quantity",
        route: "/creditcard/5",
        description: "Quantidade de cartões que deve retornar",
        options: [
          {
            name: "Números Inteiros",
            description: "Diz a quantidade de respostas deseja",
          },
        ],
        response: {
          code: 200,
          data: [
            {
              number: 3593347474642966,
              expiration: "18/12/2022",
              cvv: 559,
            },
            {
              number: 3593347474642966,
              expiration: "18/12/2022",
              cvv: 559,
            },
            {
              number: 3593347474642966,
              expiration: "18/12/2022",
              cvv: 559,
            },
            {
              number: 3593347474642966,
              expiration: "18/12/2022",
              cvv: 559,
            },
          ],
        },
      },
    ],
  },
];
